### ISSUE TITLE
is it possible to unload invisible elements from the DOM when scrolling?

### ISSUE THREAD

**Issue by FreeeeZ** [ericzwq/lazy-load-vue3#1]

**Comment by ericzwq** [comment]
Sorry, I can't clearly know your intention. Do you want to need a callback to unload invisible elements from the DOM during scrolling, or do you want to ask whether unloading invisible elements from the DOM during scrolling will affect lazy loading, or other intentions

**Comment by FreeeeZ** [comment]
> Sorry, I can't clearly know your intention. Do you want to need a callback to unload invisible elements from the DOM during scrolling, or do you want to ask whether unloading invisible elements from the DOM during scrolling will affect lazy loading, or other intentions

Yes, I want to need a callback to unload invisible upper elements from the DOM during scrolling. Now the top elements are not removed from the DOM, this is relevant for large lists for lazy loading

**Comment by ericzwq** [comment]
Passing in the invisible elements in the `afterListen` callback may work for you

**Comment by FreeeeZ** [comment]
Thanks!
