### ISSUE TITLE
容器显示隐藏对懒加载的影响

### ISSUE THREAD

**Issue by qinyao86** [ericzwq/lazy-load-vue3#2]
你好，你的插件写的非常好，但我遇到两个问题：
1. 目前我有一个容器存放一个图片列表，在列表加载完前会隐藏该容器，加载完后进行瀑布流布局，布局完后再显示容器。容器隐藏与显示使用v-show来控制，发现当容器显示后，图片不能正常加载了。有什么办法解决么？
2. 在不隐藏容器的情况下正常使用，可是当我修改过滤规则重新加载新的数据时，总是只能读取前几个图片，需要滚动一下滚动条才能继续触发显示，尽管这些图片已经在视图的中央。
Hello, your plugin is very well written, but I have two problems:
1. At present, I have a container to store a list of images. Before the list is loaded, the container will be hidden. After loading, the waterfall layout will be performed, and the container will be displayed after the layout is completed. The hiding and display of the container is controlled by v-show, and it is found that when the container is displayed, the picture cannot be loaded normally. Is there any way to solve it?
2. It is used normally without hiding the container, but when I modify the filtering rules and reload new data, I can only read the first few pictures, and I need to scroll the scroll bar to continue to trigger the display, even though these pictures have been in the center of the view.

**Comment by ericzwq** [comment]
您可以使用导出的 listener 函数强制触发一次，import {listener} from 'lazy-load-vue3';    listener();  详细您可以查看文档 :https://www.npmjs.com/package/lazy-load-vue3
You can use the exported listener function to force a trigger once, import {listener} from 'lazy-load-vue3';    listener();  You can view the document in detail: https://www.npmjs.com/package/lazy-load-vue3


布露妮娅
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ericzwq/lazy-load-vue3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月23日(星期二) 中午1:56
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ericzwq/lazy-load-vue3] 容器显示隐藏对懒加载的影响 (Issue #2)





 
你好，你的插件写的非常好，但我遇到两个问题：
  
目前我有一个容器存放一个图片列表，在列表加载完前会隐藏该容器，加载完后进行瀑布流布局，布局完后再显示容器。容器隐藏与显示使用v-show来控制，发现当容器显示后，图片不能正常加载了。有什么办法解决么？
 
在不隐藏容器的情况下正常使用，可是当我修改过滤规则重新加载新的数据时，总是只能读取前几个图片，需要滚动一下滚动条才能继续触发显示，尽管这些图片已经在视图的中央。
 Hello, your plugin is very well written, but I have two problems:
 
At present, I have a container to store a list of images. Before the list is loaded, the container will be hidden. After loading, the waterfall layout will be performed, and the container will be displayed after the layout is completed. The hiding and display of the container is controlled by v-show, and it is found that when the container is displayed, the picture cannot be loaded normally. Is there any way to solve it?
 
It is used normally without hiding the container, but when I modify the filtering rules and reload new data, I can only read the first few pictures, and I need to scroll the scroll bar to continue to trigger the display, even though these pictures have been in the center of the view.
